## numpy array and basics 
learn about numpy with chai or code

In [ ]:
import numpy as np


## time difference between list and array

In [26]:
np_list=[1,2,3]
print(np_list*2)
np_array=np.array([1,2,3])
print(np_array*2)

import time
start = time.time()
np_list=[i*2 for i in range (100000)]
print("\n List operation time:",time.time()-start)

start=time.time()
np_array=np.arange(100000)*2
print("\n Numpy operation time:",time.time()-start) 

[1, 2, 3, 1, 2, 3]
[2 4 6]

 List operation time: 0.010776996612548828

 Numpy operation time: 0.0015268325805664062


### creating array from list



In [27]:
arr_1d= np.array([1,2,3,4,5])
print("1D Array:",arr_1d)

arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

1D Array: [1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


##Creating array from scratch

In [28]:
import numpy as np

zeros=np.zeros((3,4))
print("zeros array: \n",zeros)


ones=np.ones((3,4))
print("ones array: \n",ones)

full=np.full((2,2),7)
print("full array: \n",full)

random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0, 11, 2)
print("sequence array: \n", sequence)



zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.99763397 0.10008153 0.66722391]
 [0.20674102 0.88570818 0.65036137]]
sequence array: 
 [ 0  2  4  6  8 10]


### vector, matrices, tensor

In [29]:
vector = np.array([1, 2, 3])
print(vector)

matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)


tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])

print("tensor array:\n",tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]]
tensor array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [30]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size",arr.size)
print("Dtype:",arr.dtype)
 


Shape: (2, 3)
Dimension: 2
Size 6
Dtype: int64


### array reshaping


In [ ]:
import numpy as np
arr =np.arange(12)
print("original array:", arr)

reshape = arr.reshape((3,4))
print("reshaped array:", reshape)

flattened = reshape.flatten()
print("flattened array:", flattened)

#ravel(returns view, instead of copy)
raveled = reshape.ravel()
print("raveled array:", raveled)

# transpose array
transpose = reshape.T
print("Transposed array:", transpose)

original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
