## NUMPY ARRAY OPERATIONS
    

In [2]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing",arr[2:7])
print("With Step",arr[1:8:2])
print("Negative Indexing",arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative Indexing 8


In [3]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific Element:",arr_2d[1,2])
print("Entire Row:",arr_2d[1])
print("Entire coloumn:",arr_2d[:, 1])

Specific Element: 6
Entire Row: [4 5 6]
Entire coloumn: [2 5 8]


## Sorting 

In [ ]:
unsorted = np.array([3,1,4,1,5,6,2,90])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D Array by column",np.sort(arr_2d_unsorted, axis=0))
## axis = 0 for coloumn
## axis = 1 for row

Sorted Array [ 1  1  2  3  4  5  6 90]
Sorted 2D Array by column [[1 1]
 [2 2]
 [3 3]]


## Filter

In [11]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers:",even_number)

Even numbers: [ 2  4  6  8 10]


## Filter with Mask


In [ ]:
## mask stores expression
mask = numbers > 5
print("Numbers greater than 5",numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


## Fancy Indexing vs np.where

In [ ]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("Np Where",numbers[where_result])


[1 3 5]
(array([5, 6, 7, 8, 9]),)
Np Where [ 6  7  8  9 10]


In [23]:
condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)



['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## Adding and removing data 

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined) 



[1 2 3 4 5 6]


### array compatability

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatability Shapes", a.shape == b.shape)

Compatability Shapes False


In [ ]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print(original)
print(with_new_col) 

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[1 2 7]
 [3 4 8]]


In [ ]:

arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)## here 2 is the index 
print(deleted)##so at index 2 3 element is deleted

[1 2 4 5]
